# Generated by Django 3.2.21 on 2023-09-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_auto_20221207_2031'),
        ('nutrition', '0016_alter_logitem_options_and_more'),
    ]

    operations = [
    ]
